[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "featurizer_api_client"
authors = [{name = "Brain Diseases Analysis Laboratory", email = "galaz@vut.cz"}]
dynamic = ["version", "description"]